// Updated MLB Top 100 rankings.
// Ownership is intentionally NOT stored here.
// mlb-top-100.html matches player names against window.FANTASY_OWNERS from fantasy-owners.js.

window.TOP_100_PLAYERS = [
  {
    "rank": 1,
    "player": "Jesús Made",
    "position": "SS",
    "team": "Milwaukee Brewers",
    "level": "AA",
    "eta": "2026",
    "age": "19",
    "heightWeight": "6' 1\" / 221 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 2,
    "player": "Leo De Vries",
    "position": "SS",
    "team": "Athletics",
    "level": "AA",
    "eta": "2026",
    "age": "19",
    "heightWeight": "6' 0\" / 183 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 3,
    "player": "Eli Willits",
    "position": "SS",
    "team": "Washington Nationals",
    "level": "A+",
    "eta": "2028",
    "age": "18",
    "heightWeight": "6' 1\" / 180 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 4,
    "player": "Josue De Paula",
    "position": "OF",
    "team": "Los Angeles Dodgers",
    "level": "AA",
    "eta": "2027",
    "age": "21",
    "heightWeight": "6' 3\" / 185 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 5,
    "player": "Kade Anderson",
    "position": "LHP",
    "team": "Seattle Mariners",
    "level": "AA",
    "eta": "2027",
    "age": "21",
    "heightWeight": "6' 2\" / 179 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 6,
    "player": "Colt Emerson",
    "position": "SS",
    "team": "Seattle Mariners",
    "level": "MLB",
    "eta": "2026",
    "age": "20",
    "heightWeight": "6' 0\" / 195 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 7,
    "player": "Seth Hernandez",
    "position": "RHP",
    "team": "Pittsburgh Pirates",
    "level": "A+",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 4\" / 190 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 8,
    "player": "Franklin Arias",
    "position": "SS",
    "team": "Boston Red Sox",
    "level": "AA",
    "eta": "2027",
    "age": "20",
    "heightWeight": "5' 11\" / 170 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 9,
    "player": "Ryan Sloan",
    "position": "RHP",
    "team": "Seattle Mariners",
    "level": "AA",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 5\" / 220 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 10,
    "player": "Theo Gillen",
    "position": "OF",
    "team": "Tampa Bay Rays",
    "level": "AA",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 2\" / 195 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 11,
    "player": "Sebastian Walcott",
    "position": "SS/3B",
    "team": "Texas Rangers",
    "level": "AA",
    "eta": "2027",
    "age": "20",
    "heightWeight": "6' 4\" / 190 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 12,
    "player": "Mike Sirota",
    "position": "OF",
    "team": "Los Angeles Dodgers",
    "level": "AA",
    "eta": "2027",
    "age": "23",
    "heightWeight": "6' 2\" / 188 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 13,
    "player": "Rainiel Rodriguez",
    "position": "C",
    "team": "St. Louis Cardinals",
    "level": "AA",
    "eta": "2028",
    "age": "19",
    "heightWeight": "5' 10\" / 197 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 14,
    "player": "Max Clark",
    "position": "OF",
    "team": "Detroit Tigers",
    "level": "AAA",
    "eta": "2026",
    "age": "21",
    "heightWeight": "5' 11\" / 205 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 15,
    "player": "Walker Jenkins",
    "position": "OF",
    "team": "Minnesota Twins",
    "level": "AAA",
    "eta": "2026",
    "age": "21",
    "heightWeight": "6' 3\" / 210 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 16,
    "player": "Josuar Gonzalez",
    "position": "SS",
    "team": "San Francisco Giants",
    "level": "ROK",
    "eta": "2029",
    "age": "18",
    "heightWeight": "5' 10\" / 178 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 17,
    "player": "Caleb Bonemer",
    "position": "3B/SS",
    "team": "Chicago White Sox",
    "level": "AA",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 1\" / 195 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 18,
    "player": "Ethan Holliday",
    "position": "SS",
    "team": "Colorado Rockies",
    "level": "A",
    "eta": "2029",
    "age": "19",
    "heightWeight": "6' 2\" / 210 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 19,
    "player": "Luis Peña",
    "position": "INF",
    "team": "Milwaukee Brewers",
    "level": "A+",
    "eta": "2028",
    "age": "19",
    "heightWeight": "5' 11\" / 185 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 20,
    "player": "Zyhir Hope",
    "position": "OF",
    "team": "Los Angeles Dodgers",
    "level": "AA",
    "eta": "2027",
    "age": "21",
    "heightWeight": "5' 10\" / 193 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 21,
    "player": "George Lombard Jr.",
    "position": "INF",
    "team": "New York Yankees",
    "level": "AAA",
    "eta": "2027",
    "age": "21",
    "heightWeight": "6' 2\" / 190 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 22,
    "player": "Thomas White",
    "position": "LHP",
    "team": "Miami Marlins",
    "level": "AAA",
    "eta": "2026",
    "age": "21",
    "heightWeight": "6' 5\" / 240 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 23,
    "player": "Liam Doyle",
    "position": "LHP",
    "team": "St. Louis Cardinals",
    "level": "AA",
    "eta": "2027",
    "age": "22",
    "heightWeight": "6' 2\" / 220 lbs",
    "bats": "R",
    "throws": "L"
  },
  {
    "rank": 24,
    "player": "Braden Montgomery",
    "position": "OF",
    "team": "Chicago White Sox",
    "level": "MLB",
    "eta": "2026",
    "age": "23",
    "heightWeight": "6' 2\" / 220 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 25,
    "player": "Alfredo Duno",
    "position": "C",
    "team": "Cincinnati Reds",
    "level": "A+",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 2\" / 210 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 26,
    "player": "Noah Schultz",
    "position": "LHP",
    "team": "Chicago White Sox",
    "level": "AAA",
    "eta": "2026",
    "age": "22",
    "heightWeight": "6' 10\" / 240 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 27,
    "player": "Jamie Arnold",
    "position": "LHP",
    "team": "Athletics",
    "level": "AA",
    "eta": "2027",
    "age": "22",
    "heightWeight": "6' 1\" / 188 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 28,
    "player": "Lazaro Montes",
    "position": "OF",
    "team": "Seattle Mariners",
    "level": "AA",
    "eta": "2027",
    "age": "21",
    "heightWeight": "6' 5\" / 210 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 29,
    "player": "JoJo Parker",
    "position": "SS",
    "team": "Toronto Blue Jays",
    "level": "A",
    "eta": "2029",
    "age": "19",
    "heightWeight": "6' 2\" / 200 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 30,
    "player": "Ryan Waldschmidt",
    "position": "OF",
    "team": "Arizona Diamondbacks",
    "level": "AAA",
    "eta": "2026",
    "age": "23",
    "heightWeight": "6' 0\" / 205 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 31,
    "player": "Aidan Miller",
    "position": "SS",
    "team": "Philadelphia Phillies",
    "level": "AAA",
    "eta": "2026",
    "age": "22",
    "heightWeight": "6' 1\" / 205 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 32,
    "player": "Edward Florentino",
    "position": "OF/1B",
    "team": "Pittsburgh Pirates",
    "level": "A+",
    "eta": "2028",
    "age": "19",
    "heightWeight": "6' 3\" / 200 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 33,
    "player": "Eduardo Quintero",
    "position": "OF",
    "team": "Los Angeles Dodgers",
    "level": "A+",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 1\" / 175 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 34,
    "player": "Kaelen Culpepper",
    "position": "SS",
    "team": "Minnesota Twins",
    "level": "AAA",
    "eta": "2027",
    "age": "23",
    "heightWeight": "5' 10\" / 185 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 35,
    "player": "Ethan Salas",
    "position": "C",
    "team": "San Diego Padres",
    "level": "AA",
    "eta": "2027",
    "age": "20",
    "heightWeight": "6' 1\" / 185 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 36,
    "player": "Luis Hernández",
    "position": "SS",
    "team": "San Francisco Giants",
    "level": "ROK",
    "eta": "2030",
    "age": "17",
    "heightWeight": "5' 10\" / 172 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 37,
    "player": "Travis Sykora",
    "position": "RHP",
    "team": "Washington Nationals",
    "level": "AA",
    "eta": "2028",
    "age": "22",
    "heightWeight": "6' 6\" / 232 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 38,
    "player": "Gage Jump",
    "position": "LHP",
    "team": "Athletics",
    "level": "MLB",
    "eta": "2026",
    "age": "23",
    "heightWeight": "6' 0\" / 200 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 39,
    "player": "Ralphy Velazquez",
    "position": "1B/OF",
    "team": "Cleveland Guardians",
    "level": "AAA",
    "eta": "2027",
    "age": "21",
    "heightWeight": "6' 1\" / 240 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 40,
    "player": "Robby Snelling",
    "position": "LHP",
    "team": "Miami Marlins",
    "level": "MLB",
    "eta": "2026",
    "age": "22",
    "heightWeight": "6' 3\" / 210 lbs",
    "bats": "R",
    "throws": "L"
  },
  {
    "rank": 41,
    "player": "Eduardo Tait",
    "position": "C",
    "team": "Minnesota Twins",
    "level": "A+",
    "eta": "2028",
    "age": "19",
    "heightWeight": "6' 0\" / 175 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 42,
    "player": "Bryce Rainer",
    "position": "SS",
    "team": "Detroit Tigers",
    "level": "A+",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 3\" / 195 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 43,
    "player": "Aiva Arquette",
    "position": "SS",
    "team": "Miami Marlins",
    "level": "AA",
    "eta": "2028",
    "age": "22",
    "heightWeight": "6' 5\" / 220 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 44,
    "player": "Angel Genao",
    "position": "SS",
    "team": "Cleveland Guardians",
    "level": "AAA",
    "eta": "2026",
    "age": "22",
    "heightWeight": "5' 11\" / 150 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 45,
    "player": "Michael Arroyo",
    "position": "2B/OF",
    "team": "Seattle Mariners",
    "level": "AA",
    "eta": "2026",
    "age": "21",
    "heightWeight": "5' 10\" / 160 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 46,
    "player": "Cam Caminiti",
    "position": "LHP",
    "team": "Atlanta Braves",
    "level": "A+",
    "eta": "2027",
    "age": "19",
    "heightWeight": "6' 2\" / 195 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 47,
    "player": "Tyler Bremner",
    "position": "RHP",
    "team": "Los Angeles Angels",
    "level": "A+",
    "eta": "2026",
    "age": "22",
    "heightWeight": "6' 2\" / 190 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 48,
    "player": "Arjun Nimmala",
    "position": "SS",
    "team": "Toronto Blue Jays",
    "level": "ROK",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 0\" / 190 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 49,
    "player": "Emil Morales",
    "position": "SS",
    "team": "Los Angeles Dodgers",
    "level": "A+",
    "eta": "2029",
    "age": "19",
    "heightWeight": "6' 3\" / 191 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 50,
    "player": "Joshua Báez",
    "position": "OF",
    "team": "St. Louis Cardinals",
    "level": "AAA",
    "eta": "2026",
    "age": "23",
    "heightWeight": "6' 3\" / 220 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 51,
    "player": "JR Ritchie",
    "position": "RHP",
    "team": "Atlanta Braves",
    "level": "AAA",
    "eta": "2026",
    "age": "23",
    "heightWeight": "6' 2\" / 185 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 52,
    "player": "Jarlin Susana",
    "position": "RHP",
    "team": "Washington Nationals",
    "level": "AA",
    "eta": "2027",
    "age": "22",
    "heightWeight": "6' 6\" / 235 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 53,
    "player": "Jhonny Level",
    "position": "SS",
    "team": "San Francisco Giants",
    "level": "A+",
    "eta": "2029",
    "age": "19",
    "heightWeight": "5' 8\" / 186 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 54,
    "player": "Steele Hall",
    "position": "SS",
    "team": "Cincinnati Reds",
    "level": "ROK",
    "eta": "2029",
    "age": "18",
    "heightWeight": "5' 10\" / 180 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 55,
    "player": "Gage Wood",
    "position": "RHP",
    "team": "Philadelphia Phillies",
    "level": "AA",
    "eta": "2027",
    "age": "22",
    "heightWeight": "6' 0\" / 205 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 56,
    "player": "Anthony Eyanson",
    "position": "RHP",
    "team": "Boston Red Sox",
    "level": "AA",
    "eta": "2027",
    "age": "21",
    "heightWeight": "6' 2\" / 208 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 57,
    "player": "Hagen Smith",
    "position": "LHP",
    "team": "Chicago White Sox",
    "level": "AAA",
    "eta": "2026",
    "age": "22",
    "heightWeight": "6' 3\" / 235 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 58,
    "player": "Cooper Pratt",
    "position": "SS",
    "team": "Milwaukee Brewers",
    "level": "MLB",
    "eta": "2026",
    "age": "21",
    "heightWeight": "6' 4\" / 210 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 59,
    "player": "Emmanuel Rodriguez",
    "position": "OF",
    "team": "Minnesota Twins",
    "level": "AAA",
    "eta": "2026",
    "age": "23",
    "heightWeight": "5' 11\" / 210 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 60,
    "player": "Josue Briceño",
    "position": "C/1B",
    "team": "Detroit Tigers",
    "level": "ROK",
    "eta": "2027",
    "age": "21",
    "heightWeight": "6' 4\" / 200 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 61,
    "player": "Nate George",
    "position": "OF",
    "team": "Baltimore Orioles",
    "level": "A+",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 0\" / 200 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 62,
    "player": "Billy Carlson",
    "position": "SS",
    "team": "Chicago White Sox",
    "level": "A",
    "eta": "2029",
    "age": "19",
    "heightWeight": "6' 1\" / 185 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 63,
    "player": "Dax Kilby",
    "position": "SS",
    "team": "New York Yankees",
    "level": "A",
    "eta": "2028",
    "age": "19",
    "heightWeight": "6' 2\" / 190 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 64,
    "player": "Cooper Ingle",
    "position": "C",
    "team": "Cleveland Guardians",
    "level": "MLB",
    "eta": "2026",
    "age": "24",
    "heightWeight": "5' 8\" / 190 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 65,
    "player": "Jonny Farmelo",
    "position": "OF",
    "team": "Seattle Mariners",
    "level": "A+",
    "eta": "2028",
    "age": "21",
    "heightWeight": "6' 1\" / 205 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 66,
    "player": "Charlie Condon",
    "position": "1B/OF",
    "team": "Colorado Rockies",
    "level": "AAA",
    "eta": "2026",
    "age": "23",
    "heightWeight": "6' 5\" / 216 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 67,
    "player": "Caden Scarborough",
    "position": "RHP",
    "team": "Texas Rangers",
    "level": "A+",
    "eta": "2027",
    "age": "21",
    "heightWeight": "6' 5\" / 185 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 68,
    "player": "Jefferson Rojas",
    "position": "SS",
    "team": "Chicago Cubs",
    "level": "AA",
    "eta": "2027",
    "age": "21",
    "heightWeight": "5' 11\" / 150 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 69,
    "player": "Luis Lara",
    "position": "OF",
    "team": "Milwaukee Brewers",
    "level": "AAA",
    "eta": "2026",
    "age": "21",
    "heightWeight": "5' 7\" / 169 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 70,
    "player": "Kendry Chourio",
    "position": "RHP",
    "team": "Kansas City Royals",
    "level": "A+",
    "eta": "2029",
    "age": "18",
    "heightWeight": "6' 0\" / 160 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 71,
    "player": "Kevin Alvarez",
    "position": "OF",
    "team": "Houston Astros",
    "level": "A",
    "eta": "2029",
    "age": "18",
    "heightWeight": "6' 3\" / 184 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 72,
    "player": "River Ryan",
    "position": "RHP",
    "team": "Los Angeles Dodgers",
    "level": "AAA",
    "eta": "2026",
    "age": "27",
    "heightWeight": "6' 2\" / 195 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 73,
    "player": "Roldy Brito",
    "position": "OF/2B",
    "team": "Colorado Rockies",
    "level": "A",
    "eta": "2028",
    "age": "19",
    "heightWeight": "5' 11\" / 183 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 74,
    "player": "Kayson Cunningham",
    "position": "SS",
    "team": "Arizona Diamondbacks",
    "level": "A+",
    "eta": "2029",
    "age": "20",
    "heightWeight": "5' 10\" / 182 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 75,
    "player": "Pedro Ramírez",
    "position": "3B/2B",
    "team": "Chicago Cubs",
    "level": "MLB",
    "eta": "2026",
    "age": "22",
    "heightWeight": "5' 9\" / 165 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 76,
    "player": "Felnin Celesten",
    "position": "SS",
    "team": "Seattle Mariners",
    "level": "A+",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 1\" / 175 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 77,
    "player": "Nathan Flewelling",
    "position": "C",
    "team": "Tampa Bay Rays",
    "level": "A+",
    "eta": "2028",
    "age": "19",
    "heightWeight": "6' 2\" / 200 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 78,
    "player": "Karson Milbrandt",
    "position": "RHP",
    "team": "Miami Marlins",
    "level": "AAA",
    "eta": "2027",
    "age": "22",
    "heightWeight": "6' 2\" / 230 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 79,
    "player": "Elmer Rodríguez",
    "position": "RHP",
    "team": "New York Yankees",
    "level": "AAA",
    "eta": "2026",
    "age": "22",
    "heightWeight": "6' 4\" / 177 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 80,
    "player": "Josiah Hartshorn",
    "position": "OF/1B",
    "team": "Chicago Cubs",
    "level": "A+",
    "eta": "2028",
    "age": "19",
    "heightWeight": "6' 0\" / 220 lbs",
    "bats": "S",
    "throws": "L"
  },
  {
    "rank": 81,
    "player": "Ronny Cruz",
    "position": "INF",
    "team": "Washington Nationals",
    "level": "A+",
    "eta": "2029",
    "age": "19",
    "heightWeight": "6' 2\" / 170 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 82,
    "player": "Eric Hartman",
    "position": "OF",
    "team": "Atlanta Braves",
    "level": "A+",
    "eta": "2029",
    "age": "20",
    "heightWeight": "6' 1\" / 185 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 83,
    "player": "Jonah Tong",
    "position": "RHP",
    "team": "New York Mets",
    "level": "AAA",
    "eta": "2026",
    "age": "23",
    "heightWeight": "6' 1\" / 180 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 84,
    "player": "Jett Williams",
    "position": "3B/SS/OF",
    "team": "Milwaukee Brewers",
    "level": "AAA",
    "eta": "2026",
    "age": "22",
    "heightWeight": "5' 7\" / 179 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 85,
    "player": "Ike Irish",
    "position": "OF/1B",
    "team": "Baltimore Orioles",
    "level": "A+",
    "eta": "2028",
    "age": "22",
    "heightWeight": "6' 2\" / 201 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 86,
    "player": "Carlos Lagrange",
    "position": "RHP",
    "team": "New York Yankees",
    "level": "AAA",
    "eta": "2026",
    "age": "23",
    "heightWeight": "6' 7\" / 248 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 87,
    "player": "Josh Hammond",
    "position": "SS/3B",
    "team": "Kansas City Royals",
    "level": "A",
    "eta": "2029",
    "age": "19",
    "heightWeight": "6' 1\" / 210 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 88,
    "player": "Justin Gonzales",
    "position": "OF",
    "team": "Boston Red Sox",
    "level": "A+",
    "eta": "2028",
    "age": "19",
    "heightWeight": "6' 5\" / 210 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 89,
    "player": "Charles Davalan",
    "position": "OF",
    "team": "Los Angeles Dodgers",
    "level": "A+",
    "eta": "2028",
    "age": "22",
    "heightWeight": "5' 9\" / 190 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 90,
    "player": "Xavier Neyens",
    "position": "3B/SS",
    "team": "Houston Astros",
    "level": "A",
    "eta": "2029",
    "age": "19",
    "heightWeight": "6' 3\" / 210 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 91,
    "player": "Edwin Arroyo",
    "position": "SS/2B",
    "team": "Cincinnati Reds",
    "level": "MLB",
    "eta": "2026",
    "age": "22",
    "heightWeight": "5' 11\" / 173 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 92,
    "player": "Christian Zazueta",
    "position": "RHP",
    "team": "Los Angeles Dodgers",
    "level": "AA",
    "eta": "2028",
    "age": "21",
    "heightWeight": "6' 3\" / 163 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 93,
    "player": "Devin Fitz-Gerald",
    "position": "INF",
    "team": "Washington Nationals",
    "level": "AA",
    "eta": "2028",
    "age": "20",
    "heightWeight": "5' 10\" / 185 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 94,
    "player": "Seaver King",
    "position": "SS",
    "team": "Washington Nationals",
    "level": "AAA",
    "eta": "2027",
    "age": "23",
    "heightWeight": "6' 0\" / 195 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 95,
    "player": "Jaxon Wiggins",
    "position": "RHP",
    "team": "Chicago Cubs",
    "level": "A+",
    "eta": "2026",
    "age": "24",
    "heightWeight": "6' 6\" / 225 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 96,
    "player": "Francisco Renteria",
    "position": "OF",
    "team": "Philadelphia Phillies",
    "level": "ROK",
    "eta": "2031",
    "age": "17",
    "heightWeight": "6' 3\" / 216 lbs",
    "bats": "R",
    "throws": "R"
  },
  {
    "rank": 97,
    "player": "Josh Adamczewski",
    "position": "OF",
    "team": "Milwaukee Brewers",
    "level": "AA",
    "eta": "2028",
    "age": "21",
    "heightWeight": "5' 11\" / 190 lbs",
    "bats": "L",
    "throws": "R"
  },
  {
    "rank": 98,
    "player": "James Tibbs III",
    "position": "1B/OF",
    "team": "Los Angeles Dodgers",
    "level": "AAA",
    "eta": "2027",
    "age": "23",
    "heightWeight": "5' 11\" / 201 lbs",
    "bats": "L",
    "throws": "L"
  },
  {
    "rank": 99,
    "player": "Caden Bodine",
    "position": "C",
    "team": "Tampa Bay Rays",
    "level": "A+",
    "eta": "2029",
    "age": "22",
    "heightWeight": "5' 10\" / 200 lbs",
    "bats": "S",
    "throws": "R"
  },
  {
    "rank": 100,
    "player": "Braylon Doughty",
    "position": "RHP",
    "team": "Cleveland Guardians",
    "level": "A+",
    "eta": "2028",
    "age": "20",
    "heightWeight": "6' 0\" / 203 lbs",
    "bats": "R",
    "throws": "R"
  }
];
